security:
    providers:
        akiltook_account_provider:
            id: App\Provider\AccountProvider
            # entity:
            #     class: App\Entity\Account
            #     property: email

    encoders:
        App\Entity\Account:
            algorithm: argon2i
            memory_cost:          16384 # Amount in KiB. 16 MiB
            time_cost:            2 # Number of iterations
            threads:              4 # Number of parallel threads

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_PARTNER: ROLE_PARTNER
        ROLE_ADMIN: ROLE_ADMIN

    firewalls:
        register:
            pattern: ^/accounts
            methods: [POST]
            stateless: true
            anonymous: true

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: akiltook_account_provider
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                login_path:        /login
                use_forward:       false
                oauth_user_provider:
                    service: App\Provider\AccountProvider
            json_login:
                check_path: /login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        personnal_get:
            pattern:   ^/accounts
            provider: akiltook_account_provider
            methods: [GET]
            stateless: true
            guard:
                authenticators:
                  - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern:   ^/
            provider: akiltook_account_provider
            methods: [POST, PUT, DELETE]
            stateless: true
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                login_path:        /login
                # login_path:        /connect
                use_forward:       false
                failure_path:      /login
                oauth_user_provider:
                    service: App\Provider\AccountProvider
            guard:
                authenticators:
                  - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/accounts, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }
